### ISSUE TITLE
Windows Process Id. Discovery Fails

### ISSUE THREAD

**Issue by michaelahlers** [flapdoodle-oss/de.flapdoodle.embed.process#45] opened 2016-08-17 20:05 UTC
Calls to `de.flapdoodle.embed.process.runtime.Processes#windowsProcessId` return `null`, and emit the following error (when `AbstractProcess` is instantiated):

```
java.lang.UnsatisfiedLinkError: Can't obtain updateLastError method for class com.sun.jna.Native
    at com.sun.jna.Native.initIDs(Native Method)
    at com.sun.jna.Native.<clinit>(Native.java:139)
    at com.sun.jna.platform.win32.Kernel32.<clinit>(Kernel32.java:32)
    at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:113)
    at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:51)
    at de.flapdoodle.embed.process.runtime.Processes$PidHelper$2.getPid(Processes.java:209)
    at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:72)
    at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:64)
    at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:205)
    at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:98)
```

Subsequent calls to `windowsProcessId` then emit:

```
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.platform.win32.Kernel32
    at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:113)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at flapdoodle.embed.process.issue45.ProcessesTest.verifyWindowsProcessId(ProcessesTest.java:87)
```

[A build hosted by AppVeyor](https://ci.appveyor.com/project/michaelahlers/flapdoodle-embed-process-issue-45) demonstrates the issue. See [relevant sample project](https://github.com/michaelahlers/flapdoodle-embed-process_issue-45).

**Comment by altrive** [comment] 2017-04-23 19:21
I've confirmed same error on AppVeyor windows build.
It seems to be resolved by adding "-Djna.nosys=true" JVM option.

https://ci.appveyor.com/project/altrive/flapdoodle-embed-process-issue-45/build/2

**Comment by michaelahlers** [comment] 2017-04-23 21:41
@altrive, that's a great find. Based on that, I found a related issue at native-access/jna#384.

**Closed as completed** 2022-07-21 16:32 UTC
Labels: enhancement
