### ISSUE TITLE
Incorrect OS bitness detection

### ISSUE THREAD

**Issue by arteam** [flapdoodle-oss/de.flapdoodle.embed.process#32] opened 2015-08-31 08:44 UTC
I am running a 32-bit JVM on a 64-bit Linux machine.

``` bash
$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) Client VM (build 25.25-b02, mixed mode)
$ uname -a
Linux arteam 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 
UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

`System.getProperty("os.arch")` call returns _i386_.  But my system is 64-bit anyway, regardless of bitness of the JVM. I guess it's not a very common combination, but some users still use it. 

On a 64-bit JVM detection works quite fine.

**Comment by ogerardin** [comment] 2019-01-31 10:41
After some digging around I found the explanation and a solution here: https://stackoverflow.com/a/5940770/170637

So I substituted the default BitSize with the following code:

```
   private static BitSize getOsBitness() {
        if (Platform.detect() == Platform.Windows) {
            // We want the actual OS bitness (not the JVM bitness)
            String arch = System.getenv("PROCESSOR_ARCHITECTURE");
            String wow64Arch = System.getenv("PROCESSOR_ARCHITEW6432");
            return (((arch != null) && arch.endsWith("64"))
                    || ((wow64Arch != null) && wow64Arch.endsWith("64")))
                    ? BitSize.B64 : BitSize.B32;
        }
        return BitSize.detect();
    }
```

I have confirmed that when running in a 32-bit JVM on a 64-bit Windows, I can successfully download and run a 64-bit MongoDB.

Since the whole point of this project is to run external commands, It's the OS bitness that really matters, not the JVM bitness, so I would suggest altering `BitSize.detext()` to reflect this.

**Comment by Loki-Afro** [comment] 2019-01-31 20:07
@ogerardin 

> Since the whole point of this project is to run external commands, It's the OS bitness that really matters, not the JVM bitness, so I would suggest altering BitSize.detect() to reflect this.

I agree, but windows is just one world. On Linux you can't even start the java 32 bit binary if you are on a 64 bit system, maybe that changed (knowledge from 2016 ...).

**Comment by ogerardin** [comment] 2019-01-31 21:58
> I agree, but windows is just one world. On Linux you can't even start the java 32 bit binary if you are on a 64 bit system, maybe that changed (knowledge from 2016 ...).

Well that would mean this particular problem doesn't exist in the Linux world at least :) It seems indeed to be a Windows-specific issue as Windows tries hard to make 32-bit applications believe they're running in a 32-bit OS, and my fix only targets Windows.

Any chance to see this change incorporated in the future? I can submit a PR if you'd prefer that.

**Comment by Loki-Afro** [comment] 2019-01-31 22:17
And regarding the java.com-32 bit-windows mess ... who uses java.com to download a jdk? no one and this installation routine dosen't have that issue. 

This library is intended for (unit/integration) testing so I'm pretty sure you have installed a jdk.

The only valid point when this issue might bite you if you are running tests with a 32 bit jdk and a 64 bit jdk for sanity reasons - but let's face it you'll never do that anyway with this kinda library.

Is there any point in using a 32 bit jvm on a 64 bit system?

**Comment by ogerardin** [comment] 2019-02-01 10:13
Well, Java on the desktop might be dead for fat clients and applets, but I'm trying to build a Java daemon/service that can be installed by an end-user, hence the reference to java.com. 
I know that this library is intended to facilitate testing, but it also works perfectly in this scenario because it avoids having to download, install and configure MongoDB separately, something an end-user is not expected to do.
So, there is probably no point in running a 32-bit JVM on a 64-bit OS if you know what you're doing, but it's a situation that happens and I need to consider it. My workaround works, but it's yet more noise added to my custom EmbeddedMongo configuration: originally I had
```
        val executable = mongodStarter.prepare(mongodConfig);
```
now I need to do 
```
        val distribution = new Distribution(mongodConfig.version(), Platform.detect(), getOsBitness());
        val executable = mongodStarter.prepare(mongodConfig, distribution);

```
with `getOsBitness()` as posted earlier.

**Comment by Loki-Afro** [comment] 2019-02-01 11:14
dosen't look too bad for me.
In every project you end up with some customisations ... you can't make everyone happy with some defaults, thats why you can overwrite these method to do these customisations

Some of the things I do usually 
- Pin tests to a specific mongo version
- Some project specific codecs if necessary

I'm closing this issue for now and thanks for the input :)

P.S.:
and regarding your `getOsBitness` method - heard that it would be enough to check if the String contains "64" but could be wrong ..

**Closed by Loki-Afro** 2019-02-01 11:14 UTC

**Comment by ogerardin** [comment] 2019-02-01 11:58
Fair enough. 

To be honest the thing I'm most unhappy about is that I can't inherit Spring's EmbeddedMongoAutoConfiguration and override some methods because they are private, so I had to copy much of the code to provide my own configuration...

**Comment by Loki-Afro** [comment] 2019-02-01 12:00
@ogerardin well thats the pain and gain game of spring boot ... perfect to prototype .. but in the real ...
